### ISSUE TITLE
no matching function for call to ‘get(IODImagePixelVariant

### ISSUE THREAD

**Issue by jiapei100** [PACSinTERRA/dcmtk#2]
I'm using Ubuntu 16.04.1
GCC 5.4.0

To build dcmtk git, I obtained the following error message

> /dcmtk/dcmiod/include/dcmtk/dcmiod/iodimage.h:173:22: error: no matching function for call to ‘get(IODImagePixelVariant<IODImagePixelModule<unsigned char>, IODImagePixelModule<unsigned char>, IODDoubleFloatingPointImagePixelModule, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil, OFvariadic_nil>*)’
>        return OFget<T>(&(m_ImagePixel = T(getData(),getRules())))->read(dataset);

Any suggestions please?

**Comment by boxerab** [comment]
Sorry, don't have time to support this project at the moment. Good luck!
